apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o45xko7j3-go
  janus-idp.io/tekton: o45xko7j3-go
  backstage.io/kubernetes-id: o45xko7j3-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o45xko7j3-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
